# Groups
- id: primary-controller-exlb
  type: group
  role: [primary-controller-exlb, primary-mongo, mongo]
  requires: [deploy_start]
  required_for: [deploy_end]
  parameters:
    strategy:
      type: one_by_one
  tasks:
    - copy_haproxy_keys
    - openstack-network-server-nova
    - copy_keys_ceph
    - clear_nodes_info
    - sync_time
    - swift-rebalance-cron
    - copy_keys
    - rsync_core_puppet
    - pre_hiera_config
    - override_configuration
    - upload_configuration
    - hiera
    - setup_repositories
    - fuel_pkgs
    - globals
    - logging
    - tools
    - umm
    - netconfig
    - connectivity_tests
    - firewall
    - ssl-keys-saving
    - ssl-add-trust-chain
    - ssl-dns-setup
    - hosts
    - primary-cluster
    - cluster-vrouter
    - virtual_ips
    - conntrackd
    - cluster_health
    - primary-cluster-haproxy
    - openstack-haproxy-ceilometer
    - openstack-haproxy-horizon
    - openstack-haproxy-nova
    - openstack-haproxy-sahara
    - openstack-haproxy-glance
    - openstack-haproxy-heat
    - openstack-haproxy-cinder
    - openstack-haproxy-keystone
    - openstack-haproxy-murano
    - openstack-haproxy-stats
    - openstack-haproxy-ironic
    - openstack-haproxy-radosgw
    - openstack-haproxy-swift
    - openstack-haproxy-neutron
    - openstack-haproxy-mysqld
    - openstack-haproxy
    - primary-database
    - keystone-db
    - glance-db
    - ironic-db
    - neutron-db
    - murano-db
    - nova-db
    - cinder-db
    - sahara-db
    - heat-db
    - primary-dns-server
    - primary-rabbitmq
    - murano-rabbitmq
    - apache
    - api-proxy
    - memcached
    - keystone
    - sahara-keystone
    - neutron-keystone
    - cinder-keystone
    - glance-keystone
    - glance
    - ironic-keystone
    - ironic-api
    - ceilometer-keystone
    - ceilometer-controller
    - murano-keystone
    - openstack-cinder
    - workloads_collector_add
    - heat-keystone
    - nova-keystone
    - openstack-controller
    - ironic-compute
    - openstack-network-start
    - openstack-network-common-config
    - primary-openstack-network-agents-dhcp
    - openstack-network-server-config
    - primary-openstack-network-agents-metadata
    - primary-openstack-network-plugins-l2
    - openstack-network-networks
    - openstack-network-routers
    - primary-openstack-network-agents-l3
    - openstack-network-end
    - primary-swift
    - heat
    - primary-ceph-mon
    - ceph-radosgw
    - horizon
    - murano
    - sahara
    - controller_remaining_tasks
    - vmware-vcenter
    - vcenter_compute_zones_create
    - updatedb
    - dns-client
    - ntp-check
    - ntp-server
    - ceph_create_pools
    - ceph_ready_check
    - enable_rados
    - ceilometer-radosgw-user
    - public_vip_ping
    - openstack-network-routers-ha
    - dump_rabbitmq_definitions
    - enable_quorum
    - upload_cirros
    - disable_keystone_service_token
    - ironic_upload_images
    - upload_nodes_info
    - update_hosts
    - swift-keystone
    - murano-cfapi-keystone
    - murano-cfapi
    - ironic_post_swift_key

- id: controller-exlb
  type: group
  role: [controller-exlb]
  requires: [primary-controller-exlb]
  required_for: [deploy_end, compute, compute-vmware, cinder, cinder-block-device, cinder-vmware, ceph-osd, virt, ironic]
  parameters:
    strategy:
      type: parallel
      amount: 6
  tasks:
    - copy_haproxy_keys
    - copy_keys_ceph
    - clear_nodes_info
    - sync_time
    - disable_keystone_service_token
    - copy_keys
    - rsync_core_puppet
    - pre_hiera_config
    - override_configuration
    - upload_configuration
    - hiera
    - setup_repositories
    - fuel_pkgs
    - globals
    - logging
    - tools
    - umm
    - netconfig
    - connectivity_tests
    - firewall
    - ssl-keys-saving
    - ssl-add-trust-chain
    - ssl-dns-setup
    - hosts
    - cluster
    - cluster-vrouter
    - virtual_ips
    - cluster-haproxy
    - openstack-haproxy-ceilometer
    - openstack-haproxy-horizon
    - openstack-haproxy-nova
    - openstack-haproxy-sahara
    - openstack-haproxy-glance
    - openstack-haproxy-heat
    - openstack-haproxy-cinder
    - openstack-haproxy-keystone
    - openstack-haproxy-murano
    - openstack-haproxy-stats
    - openstack-haproxy-ironic
    - openstack-haproxy-radosgw
    - openstack-haproxy-swift
    - openstack-haproxy-neutron
    - conntrackd
    - cluster_health
    - openstack-haproxy-mysqld
    - openstack-haproxy
    - dns-server
    - database
    - ceilometer-controller
    - rabbitmq
    - murano-rabbitmq
    - ironic-api
    - apache
    - api-proxy
    - glance
    - memcached
    - keystone
    - openstack-cinder
    - openstack-controller
    - ironic-compute
    - openstack-network-start
    - openstack-network-common-config
    - openstack-network-server-config
    - openstack-network-plugins-l2
    - openstack-network-agents-l3
    - openstack-network-server-nova
    - openstack-network-agents-dhcp
    - openstack-network-agents-metadata
    - openstack-network-end
    - heat
    - horizon
    - murano
    - murano-cfapi
    - sahara
    - ceph-mon
    - ceph-radosgw
    - swift
    - controller_remaining_tasks
    - vmware-vcenter
    - swift-rebalance-cron
    - updatedb
    - enable_rados
    - ceilometer-radosgw-user
    - dns-client
    - ntp-check
    - ntp-server
    - ceph_create_pools
    - public_vip_ping
    - dump_rabbitmq_definitions
    - upload_nodes_info
    - update_hosts

# Tasks
- id: external-lb-hiera
  type: puppet
  groups: [primary-controller-exlb, controller-exlb, compute, compute-vmware, cinder, cinder-block-device, cinder-vmware, primary-mongo, mongo, ceph-osd, virt, ironic]
  requires: [deploy_start]
  required_for: [hiera]
  parameters:
    puppet_manifest: puppet/manifests/create_hiera_config.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

- id: external-lb-ovs-to-ns-port
  type: puppet
  groups: [primary-controller-exlb, controller-exlb]
  requires: [deploy_start, netconfig, cluster-vrouter]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/ovs_to_ns_ocf.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
