- id: external-lb-hiera
  type: puppet
  role: '*'
  requires: [pre_hiera_config]
  required_for: [pre_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/create_hiera_config.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360
- id: external-lb-ovs-to-ns-port
  type: puppet
  groups: [primary-controller, controller]
  requires: [deploy_start, netconfig, cluster-vrouter]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/ovs_to_ns_ocf.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
