# Groups
- id: primary-controller-exlb
  type: group
  role: [primary-controller-exlb, primary-mongo, mongo]
  requires: [deploy_start]
  required_for: [deploy_end]
  parameters:
    strategy:
      type: one_by_one

- id: controller-exlb
  type: group
  role: [controller-exlb]
  requires: [primary-controller-exlb]
  required_for: [deploy_end, compute, compute-vmware, cinder, cinder-block-device, cinder-vmware, ceph-osd, virt, ironic]
  parameters:
    strategy:
      type: parallel
      amount: 6

# Tasks
- id: external-lb-hiera
  type: puppet
  groups: [primary-controller-exlb, controller-exlb, compute, compute-vmware, cinder, cinder-block-device, cinder-vmware, primary-mongo, mongo, ceph-osd, virt, ironic]
  requires: [deploy_start]
  required_for: [hiera]
  parameters:
    puppet_manifest: puppet/manifests/create_hiera_config.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

- id: external-lb-ovs-to-ns-port
  type: puppet
  groups: [primary-controller-exlb, controller-exlb]
  requires: [deploy_start, netconfig, cluster-vrouter]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/ovs_to_ns_ocf.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
