- id: external-lb-hiera
  type: puppet
  role: '*'
  requires: [deploy_start]
  required_for: [hiera]
  parameters:
    puppet_manifest: puppet/manifests/create_hiera_config.pp
    puppet_modules: /etc/puppet/modules
    timeout: 360
